---

- name: Garantir a instalacao do docker no Debian
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg2']
    update_cache: true
    state: present

- name: Adicionando a chave gpg
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: adidiconando o repositorio do docker
  apt_repository:
    repo: " deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Instalando o Docker
  apt:
    name: ['docker-ce', 'containerd.io']
    update_cache: true
    state: present
  notify:
    - start docker
